---
- name: Update apt cache
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
  tags: install

- name: Install vagrant and vagrant-libvirt
  become: yes
  become_method: sudo
  apt:
    name:
      - vagrant
      - vagrant-libvirt
    state: present
  tags: install

- name: Install vagrant and vagrant-libvirt
  become: yes
  become_method: sudo
  apt:
    name:
      - vagrant
      - ruby-libvirt
    state: build-dep
  tags: install

- name: Installs the vagrant-libvirt build dependencies in case of manual update
  command: "vagrant plugin install vagrant-libvirt"
